# Generated by Django 3.1.3 on 2020-11-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsmodel',
            old_name='parts_html',
            new_name='template',
        ),
    ]
